"""Extension contract only: no hardware connection or telemetry is simulated."""
from typing import Protocol

class DroneAdapter(Protocol):
    def connect(self, endpoint: str) -> None: ...
    def video_source(self) -> str: ...
    def telemetry(self) -> dict:
        """Timestamped GPS/altitude/IMU/RTK/PPK; missing fields must be None."""
        ...
    def disconnect(self) -> None: ...
