[server]
address = "127.0.0.1"
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#58bdd1"
backgroundColor = "#0d141c"
secondaryBackgroundColor = "#111c27"
textColor = "#e1e9ef"
font = "sans serif"
